apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  namespace: frontend

spec:
  type: LoadBalancer

  selector:
    app: web-server-pod

  ports:
    - port: 80
      targetPort: 80
      # nodePort: 30080
