apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication-deployment
  namespace: backend
spec:
  replicas: 3

  selector:
    matchLabels:
      app: authentication-pod

  template:
    metadata:
      labels:
        app: authentication-pod
        tier: backend
    spec:
      containers:
        - name: authentication-container
          image: cesarmerjan/authentication:0.0.1
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "200m"
          ports:
            - containerPort: 5000
