apiVersion: v1
kind: Service
metadata:
  name: authentication-service
  namespace: backend
spec:
  type: ClusterIP

  selector:
    app: authentication-pod

  ports:
    - port: 5000
      targetPort: 5000
