apiVersion: v1
kind: PersistentVolume
metadata:
  name: authentication-database-volume
  namespace: backend
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: slow
  hostPath:
    path: "/var/lib/data"
