apiVersion: v1
kind: Pod
metadata:
  name: authentication-database-pod
  namespace: backend
  labels:
    app: authentication-database-app
spec:
  volumes:
    - name: storage
      persistentVolumeClaim:
        claimName: authentication-database-volume-claim

  containers:
    - name: authentication-database-container
      image: postgres
      resources:
        requests:
          memory: "128Mi"
          cpu: "500m"
        limits:
          memory: "256Mi"
          cpu: "1000m"
      ports:
        - containerPort: 5432

      envFrom:
        - configMapRef:
            name: database-configmap

      volumeMounts:
        - mountPath: "/var/lib/postgresql/data"
          name: storage
