apiVersion: v1
kind: Service
metadata:
  name: authentication-database-service
  namespace: backend
spec:
  type: ClusterIP

  selector:
    app: authentication-database-app

  ports:
    - port: 5432
      targetPort: 5432
