apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: authentication-database-volume-claim
  namespace: backend
spec:
  storageClassName: slow
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
